openapi: 3.0.0
info:
  title: Empleados API
  version: "1.0"
paths:
  /empleados/datos-laborales/{legajo}:
    get:
      summary: 'Obtiene informacion de los datos laborales de un empleado a traves de su legajo'
      operationId: getDatosLaboralesByLegajo
      parameters:
        - in: path
          name: legajo
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Succesful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatosLaboralesDTO'
              example:
                sector: "Marketing"
                puesto: "Community Manager"
                salario: "100.00"
                antiguedad: "5 años"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                mensaje: "No encontrado"
                detalle: "No se encontraron empleados con el valor ingresado"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                mensaje: "Error interno de servicio"
                detalle: "Error interno de servicio"


components:
  schemas:
    DatosLaboralesDTO:
      type: object
      description: "Respuesta con los datos laborales del empleado"
      properties:
        sector:
          type: string
        puesto:
          type: string
        salario:
          type: string
        antiguedad:
          type: string

    ErrorResponse:
      type: object
      description: "Respuesta con los errores detallados"
      properties:
        mensaje:
          type: string
        detalle:
          type: string